music/urls.py
from django.conf.urls import url
from . import views

app_name ='music'

urlpatterns = [
    #/music
    url(r'^music$', views.index, name='index'),

    #/music/712/
    url(r'^music/(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    #music/contact
    url(r'^contact/$', views.contact, name='contact'),

    url(r'^$', views.cover, name='cover'),

    #mailurls
    url(r'^email/$', views.email, name='email'),

    #mailurls
    url(r'^accessories/$', views.accessories, name='accessories'),

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('music.urls')),
    url(r'^news/', include('news.urls')),
    #url(r'^cover/', include('cover.urls')),

]

news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #/music
    url(r'^$', views.index, name='news'),
]

music/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genere = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    price = models.CharField(max_length=20)

    description = models.CharField(max_length=1000, default="no data", null=True)
    sensitivity = models.CharField(max_length=20, default="no data")
    frequency = models.CharField(max_length=20, default="no data")
    impedance = models.CharField(max_length=20, default="no data")
    cable = models.CharField(max_length=50, default="no data")
    noise = models.CharField(max_length=40, default="no data")

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

news/models.py
from __future__ import unicode_literals

from django.db import models

from django.utils import timezone
# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

music/forms.py
# make sure this is at the top if it isn't already
from django import forms

# our new form
class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    # the new bit we're adding
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Name:"
        self.fields['contact_email'].label = "Email:"
        self.fields['content'].label = "Message   "

music/views.py
from django.http import Http404
from django.shortcuts import render, redirect
#from django.http import HttpResponse
from .models import Album

#mailowe
from music.forms import ContactForm
from django.core.mail import EmailMessage
from django.template import Context
from django.template.loader import get_template


def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums' : all_albums,}
    return render(request, 'music/index.html', context)

def detail(request, album_id):
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("This album does not exists")
    return render(request, 'music/detail.html', {'album' : album})

def contact(request):
    return render(request, 'music/contact.html')

def cover(request):
    return render(request, 'music/cover.html')


def email(request):
    form_class = ContactForm
 # new logic!
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name'
            , '')
            contact_email = request.POST.get(
                'contact_email'
            , '')
            form_content = request.POST.get('content', '')

            # Email the profile with the
            # contact information
            template = get_template('music/email_template.txt')
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            })
            content = template.render(context)

            email = EmailMessage(
                "New contact form submission",
                content,
                "Satori Audio" +'',
                ['fr.nikon@gmail.com'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            return redirect('music:email')

    return render(request, 'music/email.html', {'form': form_class,})

def accessories(request):
    return render(request, 'music/accessories.html')

news/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post

def index(request):
    posts = Post.objects.order_by('-published_date')
    return render(request, 'news/index.html', {'posts': posts})

#def index(request):
#    posts = Post.objects.all()
#    iloscPostow = posts.count()
#    return render_to_response('news/index.html',{'iloscPostow': iloscPostow })

music/templates/music/accessories.html
{% extends 'music/base.html' %}

{% block body %}

<div class="jumbotron">
  <div class="container">
    <h1><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span> Accessories</h1>
    <p>Available accerssories to purchase</p>
    <hr>
  </div>
</div>

  <!-- LEFT PANEL -->
  <div class="row">
    <div class="col-sm-4 col-md-3">
    <div class="panel panel-default">
    <div class="panel-body">

      <h2>Satori Case</h2>
      <a href="">
          <img src="https://fu5zya-am3pap001.files.1drv.com/y4mzXHZ6ZNkoLuzmXnK0gnMPCOTWJlKMZYKgumGccMCz58Oeg5YvKB9HqFyksbUWJHURTAyNed-uxy6Bssghg4rGdprvWE3F523fd5wqgKBvd5pCzB5uZakNxo2qj4w192QxYGz3ItMMnYvdLRiDax5HlWZZBzh-DZbUfdhGJoGIX1U9vjZKpZ-aaB67d5mkuaPUkJACP7vjD5fSqgPa_k_nw?width=660&height=373&cropmode=none" class="img-responsive">
         </a>
         <h2>Price: 29 £</h2>
         <h2></h2>


  </div>
  </div>
  </div>
    <!-- RIGHT PANNEL -->
  <div class="col-sm-8 col-md-9">
  <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Details</div>
  <div class="panel-body">
      <p>
          Durable satori case/box for transportation purposes. Available in black or transparent colour.
      </p>
  </div>
  <!-- Table -->
  <table class="table">
      <tbody>

          <tr>
              <td>in stock</td>
          </tr>

      </tbody>
  </table>
</div>
 </div>
</div>

<div class="row">
  <div class="col-sm-4 col-md-3">
  <div class="panel panel-default">
  <div class="panel-body">

    <h2>Satori Soft Cable</h2>
    <a href="">
        <img src="https://fu5aya-am3pap001.files.1drv.com/y4m-OuwaaU9q9aoddpmBCBV1yE-ZblT8_tWfyv5kikBks6phOaXgCOOlV2rNZrEjNoi65Dsfwa5DUunigGwwZCnrE2Gn2t4RtGkS0eyN00J3KhANr1-5cgNs9nbyp1B43eVj2aD5Z3Xtc3rDWN-Em1WGnZxn1DlmBnOFAq_Uejd8oRrYuT8iwQc025xLhPsQf2sLgRa_IB8Q2ViU4-sc168qQ?width=660&height=371&cropmode=none" class="img-responsive">
       </a>
       <h2>Price: 35 £</h2>
       <h2></h2>


</div>
</div>
</div>
  <!-- RIGHT PANNEL -->
<div class="col-sm-8 col-md-9">
<div class="panel panel-default">
<!-- Default panel contents -->
<div class="panel-heading">Details</div>
<div class="panel-body">
    <p>
        Soft satori replacable cable for custom made and universal monitors.
    </p>
</div>
<!-- Table -->
<table class="table">
    <tbody>

        <tr>
            <td>in stock</td>
        </tr>

    </tbody>
</table>
</div>
</div>
</div>

<div class="row">
  <div class="col-sm-4 col-md-3">
  <div class="panel panel-default">
  <div class="panel-body">

    <h2>Satori Soft Cable with mic</h2>
    <a href="">
        <img src="https://fu5aya-am3pap001.files.1drv.com/y4m-OuwaaU9q9aoddpmBCBV1yE-ZblT8_tWfyv5kikBks6phOaXgCOOlV2rNZrEjNoi65Dsfwa5DUunigGwwZCnrE2Gn2t4RtGkS0eyN00J3KhANr1-5cgNs9nbyp1B43eVj2aD5Z3Xtc3rDWN-Em1WGnZxn1DlmBnOFAq_Uejd8oRrYuT8iwQc025xLhPsQf2sLgRa_IB8Q2ViU4-sc168qQ?width=660&height=371&cropmode=none" class="img-responsive">
       </a>
       <h2>Price: 39 £</h2>
       <h2></h2>


</div>
</div>
</div>
  <!-- RIGHT PANNEL -->
<div class="col-sm-8 col-md-9">
<div class="panel panel-default">
<!-- Default panel contents -->
<div class="panel-heading">Details</div>
<div class="panel-body">
    <p>
        Soft satori replacable cable with microphone for custom made and universal monitors.
    </p>
</div>
<!-- Table -->
<table class="table">
    <tbody>

        <tr>
            <td>in stock</td>
        </tr>

    </tbody>
</table>
</div>
</div>
</div>

</ul>



<hr>
<footer>
  <p>&copy; 2016 Company, Inc.</p>
</footer>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Satori Audio{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

      <!--- Header (logo i przycisk jak strona jest waska) -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'music:cover' %}"><img src="{% static 'music/images/menulogo.png' %}">
        </a>
        <a class="navbar-brand" href="{% url 'music:cover' %}" style="font-family: Solid Edge Stencil"></a>
      </div>

      <!--- Items -->
      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li class="">
            <a href="{% url 'news' %}">
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>&nbsp; News &nbsp; <span class="badge">{{ posts.count }}</span>
            </a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'music:index' %}">Custom Made Monitors</a></li>
                <li><a href="{% url 'music:index' %}#universal">Universal Monitors</a></li>
                <li><a href="{% url 'music:index' %}#ER">ER's</a></li>
                <li role="separator" class="divider"></li>
                <li class="disabled"><a href="#">Sleeping Plugs</a></li>
                <li class="disabled"><a href="#">Swim Plugs</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'music:accessories' %}">Accessories</a></li>
            </ul>
          </li>
          <li class="">
            <a href="#">
              <span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>&nbsp; About
            </a>
          </li>
          <li class="">
            <a href="{% url 'news' %}#contact">
              <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>&nbsp; Contact Us
            </a>
          </li>
        </ul>


        <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="{% url 'music:email' %}"><i class="fa fa-envelope"></i></a>
            </li>
            <li class="">
                <a href="#"><i class="fa fa-facebook-square"></i></a>
            </li>
            <li>
                <a href="{% url 'admin:index' %}"><i class="fa fa-cogs"></i> Admin</a>
            </li>
        </ul>
      </div>

    </div>
</nav>

{% block body %}
{% endblock %}


</body>
</html>

music/templates/music/contact.html
{% extends 'music/base.html' %}
{% block title %}Contact us{% endblock %}
{% block body %}
    <div id="contact"></div>
    <div class="jumbotron">
      <div class="container">
        <h1> <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>&nbsp;Contact Us</h1>
        <p>please feel free to ask us about our products</p>
        <hr>
    </div>
    </div>





    <div class="row">
      <div class="col-sm-6 col-md-4">
      <div class="panel panel-default">
      <div class="panel-body">

          <h2><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp; satoriaudio@outlook.com</h2>
          <h2><span class="glyphicon glyphicon-phone" aria-hidden="true"></span>&nbsp; 07475 022 228</h2>
          <h2><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; RG14 2ER, Newbury, Berkshire</h2>


    </div>
    </div>
    </div>

      <!-- RIGHT PANNEL -->
    <div class="col-sm-6 col-md-8">
    <div class="panel panel-default">
    <div class="panel-heading">Location</div>
    <!-- Default panel contents -->

    <div class="panel-body">



    <!-- MAP -->
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">


        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
          <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>
        <![endif]-->

        <style>
          #map-container { height: 250px }
        </style>
    </head>

        <p></p>
        <div id="map-container" class="col-xs-10 col-sm-10 col-md-8 col-xs-offset-1 col-sm-offset-1 col-md-offset-2"></div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <script src="http://maps.google.com/maps/api/js?sensor=false"></script>

        <script>
          function init_map() {
            var var_location = new google.maps.LatLng(51.402009, -1.325588);

            var var_mapoptions = {
              center: var_location,
              zoom: 10
            };

            var var_marker = new google.maps.Marker({
                position: var_location,
                map: var_map,
                title:"Our Location"});

            var var_map = new google.maps.Map(document.getElementById("map-container"),
                var_mapoptions);

            var_marker.setMap(var_map);

          }

          google.maps.event.addDomListener(window, 'load', init_map);

        </script>


        </div>
  </div>
  </div>

  </div>



{% endblock %}

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Product Details{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} {{ album.genre }}</h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">


            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Pricing list</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>

                                </td>
                                <td>

                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% include 'music/productversions.html' %}
{% endblock %}

music/templates/music/email.html
{% extends 'music/base.html' %}

{% block body %}


<div class="jumbotron">
  <div class="container">
    <h1> <span class="fa fa-envelope" aria-hidden="true"></span>&nbsp;Contact Us</h1>
    <p>via contact form</p>
    <hr>
</div>
</div>

<div class="container">

<h2>Contact form:</h2>

<div class="row">
<div class="col-sm-4  col-xs-4 col-sm-offset-1">
<form role="form" action="" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</div>

</div>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

<div class="jumbotron">
  <div class="container">
    <h1><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span> Custom Made in-ear Monitors</h1>
    <p>Introducing our handcrafted monitors</p>
    <hr>
    <p1>
        All of our Custom Made Monitors come with one year warranty, durable Satori Box, Manual, Cleaning Set and 3,5 to 6,35mm Stereo Jack Plug Adaptor. All enclosed in elegant box, secured and safely shipped. Estimated turnround is 14 working days.
    </p1>
  </div>


</div>

  <!-- LEFT PANEL -->

  {% for album in all_albums %}
  <div class="row">
    <div class="col-sm-4 col-md-3">
    <div class="panel panel-default">
    <div class="panel-body">

      <h2>Model: {{ album.album_title }}</h2>
      <a href="{% url 'music:detail' album.id %}">
            {% if album.album_logo %}
                <img src="{{ album.album_logo }}" class="img-responsive">
             {% else %}
                 <h3>No image to display</h3>
             {% endif %}
         </a>
         <h2>Drivers: {{ album.genere }}</h2>
         <h2>Price from: {{ album.price }} £</h2>
         <h2></h2>
         <a class="btn btn-primary" href="{% url 'music:detail' album.id %}" role="button">available versions &raquo;</a>


  </div>
  </div>
  </div>

    <!-- RIGHT PANNEL -->
  <div class="col-sm-8 col-md-9">
  <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Description and Technical Details</div>
  <div class="panel-body">
      <p>
          {{album.description}}
      </p>
  </div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Sensitivity</th>
          <th>Frequency Response</th>
          <th>Impedance</th>
          <th>Cable</th>
          <th>Noise Insulation</th>
      </tr>
      </thead>
      <tbody>

          <tr>
              <td>{{album.sensitivity}}</td>
              <td>{{album.frequency}}</td>
              <td>{{album.impedance}}</td>
              <td>{{album.cable}}</td>
              <td>{{album.noise}}</td>
          </tr>

      </tbody>
  </table>
</div>
 </div>
</div>
   {% endfor %}
</ul>


<div class="jumbotron" id="universal">
  <div class="container">
    <h1><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span> Universal in-ear Monitors</h1>
    <p>Universal monitors for multiple users</p>
    <hr>
  </div>
</div>
<div class="row">
  <div class="col-sm-4 col-md-3">
  <div class="panel panel-default">
  <div class="panel-body">

    <h2>Model: </h2>
    <a href="#">
              <img src="https://qjbjea.bl3301.livefilestore.com/y4m4g1HLPNVpzBDX1JDEiiTkC6jMEiTu9tfzPVhhKJfKojY4XBlysrOL-GQpX0JHrvgkxHyvDDUCLautx5x3QRldYkRI0wde5o5X4vC793mn7c0X2uWtlZfZne-vQ6RmjSUhQMmhipmqkxsZdMIfpoqI9mBjUXKwUJNUQJNUPfBqisjvMvsqcqJeVO4mA4Co0iYQhNYp8Yr7v_8R0j0MuKtxw?width=660&height=371&cropmode=none" class="img-responsive">
       </a>
       <h2>Drivers:</h2>
       <h2>Price from: £</h2>
       <h2></h2>
</div>
</div>
</div>

  <!-- RIGHT PANNEL -->
<div class="col-sm-8 col-md-9">
<div class="panel panel-default">
<!-- Default panel contents -->
<div class="panel-heading">Description and Technical Details</div>
<div class="panel-body">
    <p>

    </p>
</div>

<!-- Table -->
<table class="table">
    <thead>
    <tr>
        <th>Sensitivity</th>
        <th>Frequency Response</th>
        <th>Impedance</th>
        <th>Cable</th>
        <th>Noise Insulation</th>
    </tr>
    </thead>
    <tbody>

        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

    </tbody>
</table>
</div>
</div>
</div>

<div class="jumbotron" id="ER">
  <div class="container">
    <h1><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span> ER's</h1>
    <p>Silicone Ear Plugs</p>
    <hr>
  </div>
</div>

<div class="row">
  <div class="col-sm-4 col-md-3">
  <div class="panel panel-default">
  <div class="panel-body">

    <h2>Model: ER-9, ER-15, ER-25</h2>
    <a href="#">
              <img src="" class="img-responsive">
       </a>
       <h2>Price: 79 £</h2>
       <h2></h2>
</div>
</div>
</div>

  <!-- RIGHT PANNEL -->
<div class="col-sm-8 col-md-9">
<div class="panel panel-default">
<!-- Default panel contents -->
<div class="panel-heading">Description and Technical Details</div>
<div class="panel-body">
        <p>Custom made silicone ear plugs for musicians and concerts</p>
        <p>ER-9 – 9dB reduction, recommended for vocals of classical musicians and audio engineers</p>
        <p>ER-15 – 15dB reduction, good for most musicians</p>
        <p>ER-25 – 25dB reduction, recommended for rock musicians, for clubbing and for concerts</p>
</div>

<!-- Table -->
<table class="table">
    <thead>
    <tr>
        <th>Material</th>
        <th>Shore Hardness</th>
        <th>Sound reduction</th>
        <th>Colour options</th>
    </tr>
    </thead>
    <tbody>

        <tr>
            <td>Non Allergic Sylicone</td>
            <td>40 Shore</td>
            <td>-9dB, -15dB, -25dB depending on model</td>
            <td>Translucent clear, solid colours and up to 3 colour solid marble</td>
        </tr>

    </tbody>
</table>
</div>
</div>
</div>

<hr>
<footer>
  <p>&copy; 2016 Company, Inc.</p>
</footer>

{% endblock %}

news/templates/news/index.html
{% extends "music/base.html" %}

{% block title %}Satori News{% endblock %}

{% block body %}



    <div class="jumbotron">
      <div class="container">
          <div class="container1">
            <br><br><br><br><br><br><br><br><br><br>
          </div>

             <hr class="my-1">
        <h1>experience the sound</h1>
        <p>custom made and universal monitors made by enthusiasts with passion. Outstanding quality for reasonable price.</p>

        <p>
            <a class="btn btn-primary btn-lg" href="#foo" role="button"><span class="badge">{{ posts.count }}</span> new posts &raquo;</a>&nbsp;
            <a class="btn btn-primary btn-lg" href="{% url 'music:index'%}" role="button"><span class="badge">2</span> new products &raquo;</a>
            <a class="btn btn-primary btn-lg" href="{% url 'music:index'%}" role="button"><span class="badge">24</span> new shells and faceplates &raquo;</a>
        </p>
      </div>
    </div>


    <div id="foo">
        <h2><a href="#"><span class="badge">{{ iloscPostow }}</span></a></h2>
    </div>




          <!-- Example row of columns -->
          <div class="row">
              <div class="col-xs-4 col-sm-4 col-md-3">
                  <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>News</h2>
                      {% for post in posts %}
                      <p>
                          <a href="#{{ post.title }}">{{ post.title }}</a>
                      </p>
                      {% endfor %}
                  </div>
                  </div>
              </div>

             <div class="col-md-9 col-xs-8">
            {% for post in posts %}

            <div class="col-md-4 col-sm-6 col-xs-12" >
                <div id="{{ post.title }}"></div>
              <h2><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> {{ post.title }}</h2>
              <p1>published: {{ post.published_date}}</p1>
              <p>{{ post.text }}</p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
            {% endfor %}
          </div>
      </div>










{% include 'music/contact.html' %}
      <hr>
<footer>
  <p>&copy; 2016 Satori Audio</p>
</footer>
{% endblock %}